version: "2.1"

services:
  app:
    build: app
    labels:
      io.balena.features.balena-api: 1
    volumes:
      - keys:/keys
      - cache:/cache
      - backups:/backups
    privileged: true
    tmpfs:
      - /tmp
      - /var/tmp
      - /run
      - /var/run
    # env_file: .env

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname
    restart: "no"
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: balena

volumes:
  keys:
  cache:
  backups:
