version: "2.1"

services:
  app:
    build: app
    labels:
      io.balena.features.balena-api: 1
    volumes:
      - keys:/keys
      - cache:/cache
      - backups:/backups
    privileged: true
    tmpfs:
      - /tmp
      - /var/tmp
      - /run
      - /var/run
    # env_file: .env

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname@sha256:b923d6ea886ec48125d2c49e431638d2ef6f4adac574b729b4135cfade3ffdce
    restart: "no"
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: balena

volumes:
  keys:
  cache:
  backups:
