name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  build:
    if: github.actor == github.repository_owner
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - id: balena_ci
        uses: balena-io/balena-ci@v0.4.4
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ secrets.BALENA_FLEET_SLUG }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          environment: balena-cloud.com
          versionbot: false
          create_ref: true
